language: ruby
matrix:
  include:
    - rvm: 2.6.2
      env: RUBYGEMS_VERSION=
    - rvm: 2.5.3
      env: RUBYGEMS_VERSION=
    - rvm: 2.4.5
      env: RUBYGEMS_VERSION=
    - rvm: 2.3.8
      env: RUBYGEMS_VERSION=
    - rvm: 2.2.10
      env: RUBYGEMS_VERSION=2.7.8
    - rvm: 2.1.10
      env: RUBYGEMS_VERSION=2.7.8
before_install:
  - gem update --system ${RUBYGEMS_VERSION}
  - gem pristine bundler

script:
  - bundle exec rake spec
